version: '2'

services:
  redis:
    image: redis:4
  wiola:
    image: 421p/wiola:0.7.0-2
    ports:
      - "6666:80"
      - "7777:80"
    environment:
      - WIOLA_MAX_PAYLOAD_LEN=10000000
    depends_on:
      - redis